#!/bin/bash

set -e

print_usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Build Image"
  echo
  echo "Options: "
  echo "-b                             Build Images"
  echo "-v <version>                   Version of Image to Mount/Build"
  echo "-t <num-threads>               Number of threads to use (default: 4)"
  echo
  echo "Mount Image"
  echo
  echo "Options: "
  echo "-m                             Mount image on yandasoft folder"
  echo "-i <image>                     Name of the Image"
  echo "-d                             Debug Mode (enables perf)"
  echo
  echo "Delete previous image"
  echo
  echo "Options: "
  echo "-r <version>                  Version of image to remove"
}

# container_engine=docker
container_engine=podman
version=1.0
dockerfiledir="$PWD"/deploy/docker/custom
yandasoftdir="$PWD"
build=false
mount=false
debug=false
remove=false
# mount_image="003-casarest"
mount_image="004-yandasoft-dev-base"
base_image="ubuntu:bionic"
image_to_delete_version="1.0"
num_threads="4"

build_base() {
  m4 -Dbaseimage=$base_image $dockerfiledir/001-yandabase | $container_engine build -t 001-yandabase:$version -
}

build_mpi() {
  m4 -DNUM_THREADS=$num_threads -Dlatest=$version $dockerfiledir/001b-mpich-yandabase | $container_engine build -t 001b-mpich-yandabase:$version -
}

build_casa() {
  m4 -DNUM_THREADS=$num_threads -Dlatest=$version $dockerfiledir/002-casacore | $container_engine build -t 002-casacore:$version -
  m4 -DNUM_THREADS=$num_threads -Dlatest=$version $dockerfiledir/003-casarest | $container_engine build -t 003-casarest:$version -
}

build_dev_base() {
  if [ "$(uname)" == "Darwin" ]; then
    m4 -Dlatest=$version $dockerfiledir/004-yandasoft-dev-base | $container_engine build -t 004-yandasoft-dev-base:$version -
  else
    # This creates non root user in the Dockerfile
    m4 -DLINUX -Dlatest=$version $dockerfiledir/004-yandasoft-dev-base | $container_engine build -t 004-yandasoft-dev-base:$version --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -
  fi
}

mount_yandasoft() {
  if $debug ; then
    if [ -e $dockerfiledir/seccomp-perf.json ] ; then
      $container_engine run --rm -it \
      -v $yandasoftdir:/home/yanda/yandasoft \
      -v $yandasoftdir/profile:/home/user/yandasoft-profile \
      --name yandasoft-dev \
      --security-opt seccomp=$dockerfiledir/seccomp-perf.json \
      $mount_image:$version
    else
      echo 'Cannot enable perf_event_open seccomp-perf.json does not exist'
      echo "Create a seccomp-perf.json in $dockerfiledir allowing perf_event_open"
      echo 'Please refer to https://docs.docker.com/engine/security/seccomp/'
      exit 1
    fi
  fi

  $container_engine run --rm -it \
  -v $yandasoftdir:/home/yanda/yandasoft \
  -v $yandasoftdir/profile:/home/user/yandasoft-profile \
  --name yandasoft-dev \
  $mount_image:$version
}

remove_images() {
  $container_engine rmi 001-yandabase:$image_to_delete_version
  $container_engine rmi 001b-mpich-yandabase:$image_to_delete_version
  $container_engine rmi 002-casacore:$image_to_delete_version
  $container_engine rmi 003-casarest:$image_to_delete_version
  $container_engine rmi 004-yandasoft-dev-base:$image_to_delete_version
}

if [ $# -eq 0 ]; then
  print_usage
  exit 0
fi

while getopts "bmdr:v:i:t:h?" opt
do
  case "$opt" in
  [h?])
    print_usage
    exit 0
    ;;
  b)
    build=true
    ;;
  d)
    debug=true
    ;;
  m)
    mount=true
    ;;
  r)
    remove=true
    image_to_delete_version="$OPTARG"
    ;;
  i)
    mount_image="$OPTARG"
    ;;
  t)
    num_threads="$OPTARG"
    ;;
  v)
    version="$OPTARG"
    ;;
  *)
    print_usage
    exit 1
    ;;
  esac
done

if $build ; then
  build_base
  build_mpi
  build_casa
  build_dev_base
elif $mount ; then
  mount_yandasoft
elif $remove ; then
  remove_images
else
  echo "Unknown usage"
  print_usage
fi
